### PR TITLE
[NIT-2672] Merge v1.13.15

### PR DESCRIPTION
**Pull request by amsanghi**
Merge upstream geth's v1.13.15 release into our geth fork:https://github.com/ethereum/go-ethereum/releases/tag/v1.13.15

nitro PR- https://github.com/OffchainLabs/nitro/pull/2496

# Testing done
geth and nitro tests pass

### CODE REVIEW

**Review by Tristan-Wilson — DISMISSED** [review]
Looks like a clean merge and I don't see anything concerning in the release notes.

**Comment by tsahee** [comment]
need to solve these ci errors.. possibly a go mod update or something?

**Comment by amsanghi** [comment]
> need to solve these ci errors.. possibly a go mod update or something?

Fixed the linter (GitHub workflow needed to be updated)

**Review by tsahee — APPROVED** [review]
LGTM

**Pull request merged**
